
export enum DeclarationKind {
  IMPORT = 'import',
  IMPORT_CLAUSE = 'importClause',
  NAMED_IMPORTS = 'namedImports',
  IMPORT_SPECIFIER = 'importSpecifier',
  NAMESPACED_IMPORT = 'namespacedImport',
  INTERFACE = 'interface',
  CLASS = 'klass',
  DECORATOR = 'decorator',
  NAME = 'name',
  TYPE_PARAMETER = 'typeParameter',
  TYPE_REFERENCE = 'typeReference',
  EXPRESSION_WITH_TYPE_ARGUMENTS = 'expressionWithTypeArguments',
  TYPE_ALIAS = 'typeAlias',
  TYPE_LITERAL = 'typeLiteral',
  HERITAGE = 'heritage',
  CONSTRUCTOR = 'cnstructor',
  PROPERTY = 'property',
  PROPERTY_SIGNATURE = 'propertySignature',
  METHOD = 'method',
  GETTER = 'getter',
  SETTER = 'setter',
  STRING_LITERAL = 'stringLiteral',
  TUPLE_TYPE = 'tupleType',
  ENUM = 'enum',
  ENUM_MEMBER = 'enumMember',
  VARIABLE = 'variable'
}
